python downsize_fastqgz.py --fqgz Han_influenzaA/Han_InfluenzaA_LibArep1_Control.fastq.gz 
python downsize_fastqgz.py --fqgz Han_influenzaA/Han_InfluenzaA_LibArep1_Infected.fastq.gz
python downsize_fastqgz.py --fqgz Han_influenzaA/Han_InfluenzaA_LibArep2_Infected.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_A/Marceau_DENV_GeCKO2_A_screen1.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_A/Marceau_DENV_GeCKO2_A_screen2.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_A/Marceau_DENV_GeCKO2_A_screen3.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_A/Marceau_DENV_GeCKO2_A_unselected_control.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_B/Marceau_DENV_GeCKO2_B_screen1.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_B/Marceau_DENV_GeCKO2_B_screen2.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_B/Marceau_DENV_GeCKO2_B_screen3.fastq.gz
python downsize_fastqgz.py --fqgz Marceau_DENV_Lib_B/Marceau_DENV_GeCKO2_B_unselected_control.fastq.gz